name: Deploy Laravel App

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "103.163.73.10" # Your VPS IP
          username: "ubuntu" # VPS username
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/Barta-App-Like-Social-Media
            git reset --hard
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
            sudo chown -R www-data:www-data /var/www/Barta-App-Like-Social-Media
            sudo chmod -R 775 /var/www/Barta-App-Like-Social-Media/storage /var/www/Barta-App-Like-Social-Media/bootstrap/cache
