name: Deploy-Laravel

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy to VPS on main branch push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Navigate to Project Directory and Put Application in Maintenance Mode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_KEY  }}
          username: "ubuntu"
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Barta-App-Like-Social-Media
            php artisan down
      - name: Update Codebase
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_KEY  }}
          username: "ubuntu"
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Barta-App-Like-Social-Media
            git stash
            git pull origin main
      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_KEY  }}
          username: "ubuntu"
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Barta-App-Like-Social-Media
            npm install
            npm run build
            composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Run Database Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_KEY  }}
          username: "ubuntu"
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Barta-App-Like-Social-Media
            php artisan migrate --force
      - name: Restart Queues
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_KEY  }}
          username: "ubuntu"
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Barta-App-Like-Social-Media
            php artisan queue:restart
      - name: Bring Application Back Online
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_KEY  }}
          username: "ubuntu"
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Barta-App-Like-Social-Media
            php artisan up >/dev/null
