name: Deploy-Laravel

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to VPS on master branch push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Navigate to Project Directory and Put Application in Maintenance Mode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_DIR }}
            php artisan down
      - name: Update Codebase
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_DIR }}
            git stash
            git pull origin main
      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_DIR }}
            npm install
            npm run build
            composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Run Database Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_DIR }}
            php artisan migrate --force
      - name: Restart Queues
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_DIR }}
            php artisan queue:restart
      - name: Bring Application Back Online
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_DIR }}
            php artisan up >/dev/null